site_name: EEmeter

docs_dir: "source"
extra_css:
  - "css/custom.css"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            show_bases: false
            show_root_heading: true
            show_root_toc_entry: false
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            merge_init_into_class: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_docstring_modules: false

nav:
  - EEmeter: index.md
  - Learn:
    - General Concepts: learn/index.md
    - EEmeter:
      - Daily / Billing Model: learn/daily_billing_model.md

  - Reference - Code API: 
    - eemeter Modules: 
      - Daily Model: reference/eemeter/daily_model.md
      - Billing Model: reference/eemeter/billing_model.md
      - Daily Model Settings: reference/eemeter/daily_model_settings.md
      - Hourly Model: reference/eemeter/hourly_model.md
      - Utilities: reference/eemeter/utilities.md
    

theme:
  name: "material"
  logo: "images/logo.png"
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
  
  language: en

  palette:
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: 
  - footnotes
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
